_wandb:
    value:
        cli_version: 0.26.1
        e:
            g9w3f6f368va963uwpje5bch96ekcd84:
                args:
                    - --model
                    - mobilenet
                    - --dataset
                    - ckplus
                    - --frozen
                    - "30"
                    - --epoch
                    - "150"
                    - --batchsize
                    - "32"
                    - --lr
                    - "0.0005"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "67108864"
                        used: "12288"
                email: anmero@fiec.espol.edu.ec
                executable: /home/andrea.merov2/USI/CV/cv_env/bin/python
                git:
                    commit: f735a4ad3cb0a85586343b312d7ec011182d8b06
                    remote: https://github.com/adelovelace/CV.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-3de7d9e4-36fc-35ce-3f49-b30d04fbe289
                host: compute-0-0.hpc.cedia.edu.ec
                memory:
                    total: "1081994862592"
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.41
                program: /home/andrea.merov2/USI/CV/train.py
                python: CPython 3.10.20
                root: /home/andrea.merov2/USI/CV
                slurm:
                    cluster_name: deepops
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    export_env: NONE
                    get_user_env: "1"
                    gpus: a100-sxm4-40gb:1
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: andrea.merov2
                    job_cpus_per_node: "32"
                    job_gid: "1523"
                    job_gpus: "33"
                    job_id: "9967"
                    job_name: sys/dashboard/sys/jupyter
                    job_nodelist: compute-0-0
                    job_num_nodes: "1"
                    job_partition: interactive
                    job_qos: normal
                    job_uid: "1523"
                    job_user: andrea.merov2
                    jobid: "9967"
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: compute-0-0
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /var/www/ood/apps/sys/dashboard
                    submit_host: management1.cedia.edu.ec
                    task_pid: "2568874"
                    tasks_per_node: "1"
                    topology_addr: compute-0-0
                    topology_addr_pattern: node
                    working_cluster: deepops:management1:6817:9728:109
                startedAt: "2026-05-14T21:34:21.336426Z"
                writerId: g9w3f6f368va963uwpje5bch96ekcd84
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 3
                - 13
                - 16
            "4": 3.10.20
            "5": 0.26.1
            "8":
                - 2
            "12": 0.26.1
            "13": linux-x86_64
architecture:
    value: mobilenet
batch_size:
    value: 32
dataset:
    value: ckplus
decay_interval:
    value: 50
decay_rate:
    value: 0.1
early_stopping_patience:
    value: 15
epochs:
    value: 150
grad_clip:
    value: 0.5
image_size:
    value: 224
learning_rate:
    value: 0.0005
